version: '3'

services:
  backend:
    build:
      context: .
      args:
        - DB_NAME=det83p2a7vaa38
        - DB_USER=kzjpscfbrhnxps
        - DB_PASSWORD=1cd2370abefbed2699ef0c4c49d83536247f0f28f613897e07089e8546cbd6d5
        - DB_HOST=ec2-52-2-43-242.compute-1.amazonaws.com
        - DB_PORT=5432
    command: gunicorn infograficos.wsgi:application --bind 0.0.0.0:8000
    image: desafio-infoglobo
    container_name: desafio-infoglobo
    ports:
      - '8000:8000'
    networks:
      - desafio-infoglobo
networks:
  desafio-infoglobo:
    driver: bridge