version: '3'

services:
  backend:
    build:
      context: .
      args:
        - DB_NAME=postgres
        - DB_USER=postgres
        - DB_PASSWORD=infoglobo2020
        - DB_HOST=infoglobo.cqd14oqso3um.sa-east-1.rds.amazonaws.com
        - DB_PORT=5432
    command: gunicorn infograficos.wsgi:application --bind 0.0.0.0:8000
    image: desafio-infoglobo
    container_name: desafio-infoglobo
    ports:
      - '8000:8000'
    networks:
      - desafio-infoglobo
networks:
  desafio-infoglobo:
    driver: bridge