# Generated by Django 3.0.2 on 2020-01-11 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_album', models.IntegerField()),
                ('nome_album', models.CharField(max_length=100)),
                ('tipo_album', models.CharField(max_length=50)),
                ('url_album', models.CharField(max_length=150)),
                ('url_art_sessenta', models.CharField(max_length=300)),
                ('url_art_cem', models.CharField(max_length=300)),
                ('preco_album', models.DecimalField(decimal_places=2, max_digits=5)),
                ('classificacao', models.CharField(max_length=50)),
                ('n_faixas', models.IntegerField()),
                ('copyright', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('moeda', models.CharField(max_length=20)),
                ('lancamento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_artista', models.IntegerField()),
                ('id_amg', models.IntegerField()),
                ('tipo_artista', models.CharField(max_length=30)),
                ('nome_artista', models.CharField(max_length=100)),
                ('url_artista', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='GeneroMusical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_genero', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_musica', models.IntegerField()),
                ('nome_musica', models.CharField(max_length=50)),
                ('url_musica', models.CharField(max_length=150)),
                ('url_preview', models.CharField(max_length=150)),
                ('url_art_trinta', models.CharField(max_length=150)),
                ('url_art_sessenta', models.CharField(max_length=150)),
                ('url_art_cem', models.CharField(max_length=150)),
                ('preco_musica', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lancamento', models.DateTimeField()),
                ('classificacao', models.CharField(max_length=50)),
                ('faixa_n', models.IntegerField()),
                ('tempo_musica', models.IntegerField()),
                ('pais', models.CharField(max_length=50)),
                ('moeda', models.CharField(max_length=20)),
                ('stream', models.BooleanField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Album')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Artista')),
                ('genero_musical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GeneroMusical')),
            ],
        ),
        migrations.AddField(
            model_name='artista',
            name='genero_musical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GeneroMusical'),
        ),
        migrations.AddField(
            model_name='album',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Artista'),
        ),
        migrations.AddField(
            model_name='album',
            name='genero_musical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GeneroMusical'),
        ),
    ]
