# Generated by Django 3.0.2 on 2020-01-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='lancamento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='musica',
            name='lancamento',
            field=models.CharField(max_length=20),
        ),
    ]
