# Generated by Django 3.0.2 on 2020-01-13 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200111_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artista',
        ),
        migrations.RemoveField(
            model_name='musica',
            name='album',
        ),
        migrations.RemoveField(
            model_name='musica',
            name='artista',
        ),
        migrations.AddField(
            model_name='album',
            name='musica',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.Musica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artista',
            name='album',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.Album'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artista',
            name='musica',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.Musica'),
            preserve_default=False,
        ),
    ]
