# Generated by Django 3.0.2 on 2020-01-13 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200113_0549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='album',
        ),
        migrations.RemoveField(
            model_name='artista',
            name='musica',
        ),
        migrations.AddField(
            model_name='musica',
            name='artista',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.Artista'),
            preserve_default=False,
        ),
    ]
